class FullPack

  include Cribbage

  HA = Card.new( Card::ACE, Card::HEARTS )
  H2 = Card.new( 2, Card::HEARTS )
  H3 = Card.new( 3, Card::HEARTS )
  H4 = Card.new( 4, Card::HEARTS )
  H5 = Card.new( 5, Card::HEARTS )
  H6 = Card.new( 6, Card::HEARTS )
  H7 = Card.new( 7, Card::HEARTS )
  H8 = Card.new( 8, Card::HEARTS )
  H9 = Card.new( 9, Card::HEARTS )
  HT = Card.new( Card::TEN, Card::HEARTS )
  HJ = Card.new( Card::JACK, Card::HEARTS )
  HQ = Card.new( Card::QUEEN, Card::HEARTS )
  HK = Card.new( Card::KING, Card::HEARTS )

  CA = Card.new( Card::ACE, Card::CLUBS )
  C2 = Card.new( 2, Card::CLUBS )
  C3 = Card.new( 3, Card::CLUBS )
  C4 = Card.new( 4, Card::CLUBS )
  C5 = Card.new( 5, Card::CLUBS )
  C6 = Card.new( 6, Card::CLUBS )
  C7 = Card.new( 7, Card::CLUBS )
  C8 = Card.new( 8, Card::CLUBS )
  C9 = Card.new( 9, Card::CLUBS )
  CT = Card.new( Card::TEN, Card::CLUBS )
  CJ = Card.new( Card::JACK, Card::CLUBS )
  CQ = Card.new( Card::QUEEN, Card::CLUBS )
  CK = Card.new( Card::KING, Card::CLUBS )

  DA = Card.new( Card::ACE, Card::DIAMONDS )
  D2 = Card.new( 2, Card::DIAMONDS )
  D3 = Card.new( 3, Card::DIAMONDS )
  D4 = Card.new( 4, Card::DIAMONDS )
  D5 = Card.new( 5, Card::DIAMONDS )
  D6 = Card.new( 6, Card::DIAMONDS )
  D7 = Card.new( 7, Card::DIAMONDS )
  D8 = Card.new( 8, Card::DIAMONDS )
  D9 = Card.new( 9, Card::DIAMONDS )
  DT = Card.new( Card::TEN, Card::DIAMONDS )
  DJ = Card.new( Card::JACK, Card::DIAMONDS )
  DQ = Card.new( Card::QUEEN, Card::DIAMONDS )
  DK = Card.new( Card::KING, Card::DIAMONDS )

  SA = Card.new( Card::ACE, Card::SPADES )
  S2 = Card.new( 2, Card::SPADES )
  S3 = Card.new( 3, Card::SPADES )
  S4 = Card.new( 4, Card::SPADES )
  S5 = Card.new( 5, Card::SPADES )
  S6 = Card.new( 6, Card::SPADES )
  S7 = Card.new( 7, Card::SPADES )
  S8 = Card.new( 8, Card::SPADES )
  S9 = Card.new( 9, Card::SPADES )
  ST = Card.new( Card::TEN, Card::SPADES )
  SJ = Card.new( Card::JACK, Card::SPADES )
  SQ = Card.new( Card::QUEEN, Card::SPADES )
  SK = Card.new( Card::KING, Card::SPADES )
end
